import type { Metadata } from "next";
import { Bebas_Neue, Inter, Space_Grotesk, Space_Mono } from "next/font/google";
import "./globals.css";

const bebasNeue = Bebas_Neue({
  weight: "400",
  variable: "--font-bebas-neue",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

const spaceGrotesk = Space_Grotesk({
  variable: "--font-space-grotesk",
  subsets: ["latin"],
});

const spaceMono = Space_Mono({
  weight: ["400", "700"],
  variable: "--font-space-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Toaster } from 'react-hot-toast';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${bebasNeue.variable} ${inter.variable} ${spaceGrotesk.variable} ${spaceMono.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        {children}
        <Toaster 
          position="bottom-center"
          toastOptions={{
            style: {
              background: 'var(--color-ink)',
              color: 'var(--color-canvas)',
              fontFamily: 'var(--font-inter)',
              borderRadius: '30px',
            },
            success: {
              style: {
                background: 'var(--color-success)',
              }
            },
            error: {
              style: {
                background: 'var(--color-sale)',
              }
            }
          }}
        />
      </body>
    </html>
  );
}
